// ----------------------------------------------------------------------------
// Module:      SPI
// Description: SPI master controller. Mode-0 by default (CPOL=0, CPHA=0).
//              Drives sclk, mosi, ss_n; samples miso. Caller drives start
//              to begin an 8-bit transfer; busy goes high until done.
// Parameters:  CLK_DIV - sclk = clk / (2 * CLK_DIV) (default 4)
//              CPOL    - clock polarity (default 0)
//              CPHA    - clock phase (default 0)
// Ports:       clk      - system clock
//              reset    - asynchronous reset, active high
//              start    - one-cycle pulse to begin a transfer
//              tx_data  - 8-bit data to send
//              rx_data  - 8-bit data received
//              busy     - high during transfer
//              sclk     - SPI serial clock output
//              mosi     - master-out, slave-in
//              miso     - master-in, slave-out
//              ss_n     - slave-select, active low
// Author:      Amr Said
// Date:        2026-05-14
// ----------------------------------------------------------------------------
module SPI #(
    parameter CLK_DIV = 4,
    parameter CPOL    = 0,
    parameter CPHA    = 0
)(
    input        clk,
    input        reset,
    input        start,
    input  [7:0] tx_data,
    output [7:0] rx_data,
    output       busy,
    output       sclk,
    output       mosi,
    input        miso,
    output       ss_n
);

    // TODO: implement SPI master
    // - sclk generated by dividing clk by 2*CLK_DIV, gated by busy
    // - On start: load tx_data into shift register, drive ss_n low, run for 8 sclk edges
    // - On each appropriate sclk edge (depends on CPOL/CPHA):
    //     shift out MSB on mosi
    //     sample miso into rx shift register
    // - After 8 bits: deassert ss_n high, drop busy, hold rx_data

endmodule
